# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UpdateInfo

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0/2 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: update
      run: |
        python ./writeJson.py
    # 配置 git
    - name: config git
      run: git config --global user.email "tomdejio@gmail.com"&&git config --global user.name "popoYSL"
    # 使用 git 命令
    - name: check for changes
      run: git status
    - name: git pull
      run: git pull
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "update by github actions"
    - name: push code to main
      run: git push origin main
